#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/../.env}"

TOTAL_STAGES=5

banner "Real Estate AI Video — account setup"

# ── Stage 1: OpenRouter (script writing via DeepSeek) ─────────────────────
stage "OpenRouter — sign up + API key + credit"
say "This powers the Thai script-writing step (DeepSeek via OpenRouter)."
open_url "https://openrouter.ai/"
step "Sign in with Google or GitHub (top right)."
open_url "https://openrouter.ai/settings/credits"
step "Add credit — \$5 is plenty to prototype with. OpenRouter uses Stripe checkout."
confirm "Credit added?" || warn "you can add credit later — a key still works with \$0 balance until you actually call a paid model"
open_url "https://openrouter.ai/settings/keys"
step "Click 'Create Key', name it something like 'realestate-video-prototype', copy the key (shown once)."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter API key:"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"

# ── Stage 2: Cloudflare Workers AI (photo enhancement) ──────────────────────
stage "Cloudflare — API token for Workers AI"
say "This powers the photo enhancement step (pruna/p-image-upscale on Workers AI)."
say "Replaced fal.ai 2026-08-31 — that account got locked pending a credit top-up"
say "and was never actually verified live. Same Cloudflare account already used"
say "for the MCP servers and 'wrangler login' — no new signup needed."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click 'Create Token' -> 'Create Custom Token'."
step "Give it Account > Workers AI > Edit permission, scoped to your account."
step "Create it, copy the token (shown once)."
ask_secret CLOUDFLARE_API_TOKEN "Paste the Cloudflare API token:"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
note "Account ID is on the right sidebar of any zone's Overview page in the"
note "Cloudflare dashboard, or run: wrangler whoami"
ask CLOUDFLARE_ACCOUNT_ID "Paste your Cloudflare Account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── Stage 3: SpeechGen (Thai TTS) ──────────────────────────────────────────
stage "SpeechGen.io — sign up + API access"
say "This powers the Thai voiceover step. SpeechGen's API historically needs BOTH"
say "your account email AND a separate API token (not just one key) — grab both."
open_url "https://speechgen.io/"
step "Sign up for a free account (top right)."
open_url "https://speechgen.io/en/account/"
note "look for a tab/section literally called 'API' on the account page — that's"
note "where the token lives. If you don't see it, search their site for"
note "'API' in the top nav or footer — this page moves around between plans."
step "Copy your account email and the API token shown there."
ask SPEECHGEN_EMAIL "Paste the SpeechGen account email:"
ask_secret SPEECHGEN_API_KEY "Paste the SpeechGen API token:"
write_env SPEECHGEN_EMAIL "$SPEECHGEN_EMAIL"
write_env SPEECHGEN_API_KEY "$SPEECHGEN_API_KEY"
note "check speechgen.io/en/api right after this — confirm the current free quota"
note "(it was ~1,000 chars with no signup, ~3,000/day for 7 days after signup, last"
note "checked 2026-08-25) since free-tier terms shift without notice."

# ── Stage 4: Creatomate (video assembly) ───────────────────────────────────
stage "Creatomate — sign up + project + API key"
say "This powers the final video render (photos + voiceover + text overlays)."
say "Chosen over Shotstack for this prototype: JSON template model with per-listing"
say "merge fields fits the agent-branding overlay requirement, and free trial credits"
say "are enough to render several test videos before any payment is needed."
open_url "https://creatomate.com/"
step "Sign up for a free account — confirm you land with trial credits (was 50 at last check)."
open_url "https://creatomate.com/projects"
step "Open (or create) a project — Creatomate scopes API keys per project."
step "In the project, find 'API' or 'Integrations' in the left sidebar, copy the API key."
ask_secret CREATOMATE_API_KEY "Paste the Creatomate API key:"
write_env CREATOMATE_API_KEY "$CREATOMATE_API_KEY"

# ── Stage 5: Verify nothing was skipped ────────────────────────────────────
stage "Verify"
say "Checking that all 4 services have a key on file (values themselves stay hidden)."
for pair in "OPENROUTER_API_KEY:OpenRouter" "CLOUDFLARE_API_TOKEN:Cloudflare" "CLOUDFLARE_ACCOUNT_ID:Cloudflare Account ID" "SPEECHGEN_API_KEY:SpeechGen" "CREATOMATE_API_KEY:Creatomate"; do
  key="${pair%%:*}"; label="${pair##*:}"
  val=$(_existing "$key" || true)
  if [[ -n "$val" ]]; then
    printf '  %s✓%s %s — key on file (%s chars)\n' "$GREEN" "$RESET" "$label" "${#val}"
  else
    printf '  %s✗%s %s — MISSING, re-run this wizard to fill it in\n' "$RED" "$RESET" "$label"
  fi
done

finish
note "Next: the prototype pipeline script will read these from $ENV_FILE — don't commit that file."
